### PR TITLE
Support for X86-64, choose DLL version dynamically

### PR DESCRIPTION
**Pull request by CarterLi**
~~Also targets .NET 4~~

### CODE REVIEW

**Comment by RomanBelkov** [comment]
Why do we need to retarget to v4.0 of .NET Framework?

**Comment by CarterLi** [comment]
I think it's more widely used today.
I'll revert the change if you don't like

**Comment by RomanBelkov** [comment]
Of course it is used more widely, but targeting to 2.0 Framework allows more users (with projects using older Framework versions) to add XZ.NET to their project.

If there is such a need, user can retarget a library by yourself, but I want to keep my version as comaptible as it can be (not mentioning 1.0 & 1.1, though, they're way too old)

**Comment by CarterLi** [comment]
I've reverted my change

**Pull request merged**
